# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('emailId', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
    ]
